fix function declaration error in php 7.3
moreonion/campaignion pull request #194
Opened 2019-08-27 13:41 UTC by mojulia

2019-08-27 13:55 UTC, torotil requested changes

2019-08-27 13:55 UTC, torotil commented on src/CRM/Export/DateField.php
>      if ($timestamp = parent::value()) {
`$delta` should be passed to the parent here.

2019-08-27 13:55 UTC, torotil commented on src/CRM/Export/KeyedField.php
> +    if (($values = parent::value($delta))) {
The data structure returned by `WrapperField::value()` differs depending on whether you pass `NULL` or something else (ie. the default `0`). So passing anything else than `NULL` to this function probably wouldn’t work.

2019-09-28 18:52 UTC, torotil approved these changes

2019-10-01 13:01 UTC, katzmo approved these changes

2019-10-01 13:07 UTC, merged