WIP: Restructure expiry functions
moreonion/campaignion pull request #298
Opened 2022-01-28 14:55 UTC by katomat

Goal:
Have a function for other scripts to anonymise individual contacts.
Add a little_helpers service to anonymise a contact.
Expiry Cron jobs should call it instead of providing this functionality themselves.

2022-02-23 10:16 UTC, katomat commented
![](https://github.trello.services/images/mini-trello-icon.png) [Campaignion: Expiry](https://trello.com/c/EOHDgG5v/1316-campaignion-expiry)

2022-02-23 11:49 UTC, torotil commented on campaignion_expiry/src/Anonymizer.php
> +   *   Contact that is being anonymized.
The `Anonymizer` gets the contact passed as argument to the method call not to the constructor. That would also match the service definition.

```suggestion
```

2022-02-23 11:49 UTC, torotil commented on campaignion_expiry/tests/AnonymizeContactTest.php
> +   */
A more informative comment would be nice (also below at `tearDown()`.

2022-02-23 11:49 UTC, torotil commented on campaignion_expiry/tests/AnonymizeContactTest.php
> +  }
We could/should also test `Anonymizer::deleteOldRevisions()` here.

2022-03-02 08:46 UTC, katomat commented
I added more comments and added testing for the deleteOldRevisions functions.

2022-03-02 12:53 UTC, torotil requested changes
… otherwise good enough for me :-)

2022-03-02 12:53 UTC, torotil commented on campaignion_expiry/tests/AnonymizeContactTest.php
> +use Drupal\campaignion\Contact;
Could you sort the imports alphabetically?

2022-03-02 12:53 UTC, torotil commented on campaignion_expiry/tests/AnonymizeContactTest.php
> +   *
No need to keep the worthless part of the comment. ;-)

2022-03-02 16:38 UTC, katomat commented
@torotil Wouldn't the tearDown actually require to not only delete the $this->contact, but also the actual anonymised redhen_contact?

2022-03-03 10:17 UTC, torotil commented
> @torotil Wouldn't the tearDown actually require to not only delete the $this->contact, but also the actual anonymised redhen_contact?

They are the same — as in having the same `$contact->contact_id` that’s what anonymization means after all.

2022-03-03 10:22 UTC, torotil approved these changes

2022-03-14 10:52 UTC, merged