Check if user has 'update' permission for nodes
moreonion/campaignion pull request #85
Opened 2018-02-16 11:36 UTC by m-strasser

Prevents users from circumventing access controls for (un)publishing nodes via batch jobs.

2018-02-16 11:51 UTC, torotil commented
That perhaps needs changes in ContentListing.php too to only show the links when the user has the permission.

Also we might want to report the fact that the selected bulk operation was not applied to some of the nodes because of missing permissions.

2018-02-27 14:02 UTC, torotil requested changes
A few small issues otherwise fine.

2018-02-27 14:02 UTC, torotil commented on campaignion_manage/src/ContentListing.php
> +         || ($path === 'wizard' && node_access('update', $node))) {
Could we write this more like this?

```php
$action = $path == 'wizard' ? 'update' : $path;
if (node_access($action, $node)) {
```

I think it’s more readable this way. Also it avoids calling `node_access('wizard', $node)`.

2018-02-27 14:02 UTC, torotil commented on campaignion_manage/tests/UnPublishTest.php
> +    $this->assertEmpty($msgs);
Could you add a test that shows that unpublishing a published node doesn’t work either

2018-02-27 14:02 UTC, torotil commented on campaignion_manage/src/BulkOp/ContentPublish.php
> +    $error_message = "Could not publish \"!node\" due to lacking permissions.";
Please use single quotes in this case to avoid backslashes in the string. Also we should pass this through `t()` directly otherwise .pot-extractors have difficulties picking up the string.

2018-02-27 14:02 UTC, torotil commented on campaignion_manage/src/BulkOp/ContentUnpublish.php
> +    $error_message = "Could not unpublish \"!node\" due to lacking permissions.";
Same as the other error message.

2018-02-28 09:01 UTC, torotil approved these changes

2018-02-28 09:21 UTC, torotil commented
Hm, the whole issue might be bogus. The whole manage page is not accessible unless you have the `administer content` permission:

https://github.com/moreonion/campaignion/blob/7.x-1.x/campaignion_manage/campaignion_manage.module#L5-L36

2018-02-28 11:45 UTC, m-strasser commented
The code simply checks if the user has `node_access('update'/'view'/etc., $node)` permissions for a given node and hides buttons accordingly. The `editor` role with default permissions in `pristine-camp` is an example of a user with that permission set. If `administer nodes` should grant access to CRUD operations on all content types the permissions should be set correctly and the bug lies there. I see no reason not the implement access checks on node level, otherwise we're always open to access level bypasses.

2018-03-01 11:10 UTC, torotil commented
Right. The additional checks don’t hurt and the additional tests are good too.

2018-03-01 11:11 UTC, merged