add opt-in statement to newsletter subscription
moreonion/campaignion pull request #88
Opened 2018-02-21 16:40 UTC by alex-mo

- provide a field on the component to set a statement for internal
  audit trail (will not be shown to users)
- save the text along the newsletter_subscription activity
- the activity is saved on confirmation (not on creation)

2018-02-22 17:53 UTC, torotil requested changes
Looks good in general. Could you try to also meet these criteria?

* Fix coding-style issues in all non-features files touched by the change (in a separate commit).
* Add tests (for the changes) so that the coverage over-all coverage doesn’t decrease.

I know this sets the bar higher for new code than it was for the old, but then again that’s the point isn’t it?

2018-02-24 08:56 UTC, torotil reviewed
Some of the method summaries are still a bit imprecise, but it definitely looks much better now.

2018-02-24 08:56 UTC, torotil commented on campaignion_newsletters/src/Subscription.php
> +   * Construct a new instance from data found in the DB.
Mh that should be more like "Get an instance form DB or create a new one." or something like that.

2018-02-24 08:56 UTC, torotil commented on campaignion_newsletters/src/Subscription.php
> +   * Construct a new instance from email addresses found in the DB.
That should be "Load all subscriptions for one email address." or something similar.

2018-02-24 08:56 UTC, torotil commented on campaignion_newsletters/src/Subscription.php
> +   * Get the newsletter list instance.
This needs a @return docs.

2018-02-26 15:31 UTC, alex-mo commented on campaignion_newsletters/src/Subscription.php
> +   * Construct a new instance from data found in the DB.
fine with me

2018-02-26 15:43 UTC, alex-mo commented on campaignion_newsletters/src/Subscription.php
> +   * Get the newsletter list instance.
`phpcs` is silent about that...

2018-02-26 20:27 UTC, torotil approved these changes

2018-02-26 20:27 UTC, torotil commented
Great, thanks!

2018-02-26 20:29 UTC, merged